version: '2'
services:
    nginx:
        build: nginx
        ports:
        - 8888:80
        depends_on:
        - kibana
        - grafana
        - prometheus
        - rabbitmq
        - gracc-collector
    elasticsearch:
        image: elasticsearch:5
        volumes:
        - elasticsearch:/usr/share/elasticsearch/data
    kibana:
        build: kibana
        environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
        depends_on:
        - elasticsearch
    logstash:
        build: logstash
        environment:
        - LOGSPOUT=ignore
        depends_on:
        - elasticsearch
    logspout:
        image: gliderlabs/logspout
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        command: syslog://logstash:2514
        environment:
        - SYSLOG_FORMAT=rfc3164
        depends_on:
        - logstash
    prometheus:
        build: prometheus
        volumes:
        - prometheus:/data
        command:
        - -config.file=/etc/prometheus/prometheus.yml
        - -storage.local.path=/data
        - -web.external-url=http://localhost:8888/prometheus
    cadvisor:
        image: google/cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
    prometheus-elasticsearch:
        image: thedutchselection/prometheus_elasticsearch_exporter:0.3.0
        environment:
        - ELASTICSEARCH_URI=http://elasticsearch:9200
    prometheus-rabbitmq:
        image: kbudde/rabbitmq-exporter
        environment:
        - RABBIT_URL=http://rabbitmq:15672
    grafana:
        image: grafana/grafana
        environment:
        - GF_SERVER_ROOT_URL=http://localhost:8888/grafana/
    rabbitmq:
        image: rabbitmq:management
        ports:
        - "15672:15672"
    gracc-collector:
        image: retzkek/gracc-collector
        environment:
        - GRACC_AMQP_HOST=rabbitmq
        - GRACC_AMQP_EXCHANGE=gracc.test.raw
        - GRACC_AMQP_DURABLE=true
        - GRACC_AMQP_AUTODELETE=false
        - GRACC_LOGLEVEL=debug
        command:
        - /usr/bin/gracc-collector
        - -pprof=on
        depends_on:
        - rabbitmq
    gracc-stash-raw:
        image: retzkek/gracc-stash-raw:debug
        environment:
        - GRACC_INSTANCE=test
        - GRACC_STREAM=test
        - ELASTICSEARCH_HOST=elasticsearch
        - AMQP_HOST=rabbitmq
        depends_on:
        - gracc-collector
        - elasticsearch
    gracc-request:
        image: opensciencegrid/gracc-request:latest
        depends_on:
        - rabbitmq
        - elasticsearch
        volumes:
        - ./gracc-request/gracc-request-test.toml:/etc/graccreq/config.d/gracc-request.toml 
        command: /usr/bin/graccreq -c /etc/graccreq/config.d/gracc-request.toml

volumes:
    elasticsearch:
    prometheus:

