[General]
Profile = true

[AMQP]

# Host information
url = "amqp://guest:guest@rabbitmq/"

exchange = 'gracc.osg.requests'
queue = 'gracc.osg.requests'

[ElasticSearch]
raw_index = 'gracc.osg.raw*'
raw_type = 'JobUsageRecord'
transfer_type = 'Storage'
transfer_index = 'gracc.osg-transfer.raw-*'
